### Working with Pytoch Tensors

In [19]:
import torch
import numpy as np

In [20]:
### Default datatype float32
x = torch.ones(2,2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [21]:
### Define specific datatype
x = torch.ones(2,2, dtype=torch.int8)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)
torch.int8


In [22]:
### Change datatype float64, it was int8
x = x.type(torch.float64)
print(x.dtype)

torch.float64


In [23]:
### Converting tensors into Numpy arrays
x = torch.rand(2,2)
print("Tensor x is :\n",x)
print(x.dtype)

######################################
print("#"*20)
######################################

y = x.numpy()
print("Array y is:\n",y)
print(y.dtype)

Tensor x is :
 tensor([[0.0430, 0.8640],
        [0.9734, 0.0296]])
torch.float32
####################
Array y is:
 [[0.04299253 0.86404794]
 [0.97343475 0.02957517]]
float32


In [24]:
### Convert Numpy arrays into tensors
x = np.zeros((2,2), dtype=np.float32)
print("Numpy array x is:\n",x)
print(x.dtype)

######################################
print("#"*20)
######################################

y = torch.from_numpy(x)
print("Tensor y is:\n",y)
print(y.dtype)

Numpy array x is:
 [[0. 0.]
 [0. 0.]]
float32
####################
Tensor y is:
 tensor([[0., 0.],
        [0., 0.]])
torch.float32


In [36]:
### Moving tensor between devices
# Define tensor on CPU

x = torch.tensor([1.5,2])
print("Tensor is:\n",x)
print("Tensor is on device: ",x.device)

######################################
print("#"*20)
######################################

# Define Device
if torch.cuda.is_available():
    device = torch.device('cuda:0')

# Move tensor onto the CUDA device

x = x.to(device)
print("Tensor is\n",x)
print(x.device)
# y = torch.tensor([1.5,2], device=device)

Tensor is:
 tensor([1.5000, 2.0000])
Tensor is on device:  cpu
####################
Tensor is
 tensor([1.5000, 2.0000], device='cuda:0')
cuda:0
